// src/data/MotorData.tsx

export const allMotors = [
  {
    id: 1,
    name: "Honda Vario 160",
    price: "Rp 28.500.000",
    type: "Matic",
    year: "2023",
    km: "5.200 km",
    transmission: "Otomatis",
    location: "Padang Serai",
    fullLocation: "Padang Serai, Bengkulu",
    color: "Merah",
    engine: "160cc",
    condition: "Bekas",
    image: "/id1.png",
    description:
      "Honda Vario 160 warna merah dengan kondisi bekas terawat. Motor matic ini memiliki tampilan sporty, nyaman digunakan untuk kebutuhan harian, dan irit bahan bakar.",
  },

  {
    id: 2,
    name: "Yamaha NMAX 155",
    price: "Rp 32.000.000",
    type: "Matic",
    year: "2022",
    km: "12.000 km",
    transmission: "Otomatis",
    location: "Padang Serai",
    fullLocation: "Padang Serai, Bengkulu",
    color: "Hitam",
    engine: "155cc",
    condition: "Bekas",
    image: "/id2.png",
    description:
      "Yamaha NMAX 155 warna hitam dengan kondisi bekas terawat. Motor ini nyaman digunakan untuk perjalanan harian maupun jarak jauh.",
  },

  {
    id: 3,
    name: "Honda Beat Street",
    price: "Rp 15.500.000",
    type: "Matic",
    year: "2016",
    km: "8.700 km",
    transmission: "Otomatis",
    location: "Simpang Kandis",
    fullLocation: "Simpang Kandis, Bengkulu",
    color: "Putih Biru",
    engine: "110cc",
    condition: "Bekas",
    image: "/id3.png",
    description:
      "Honda Beat Street warna putih biru dengan kondisi bekas terawat. Ringan, irit bahan bakar, dan cocok digunakan untuk aktivitas sehari-hari.",
  },

  {
    id: 4,
    name: "Yamaha Aerox 155",
    price: "Rp 26.000.000",
    type: "Matic",
    year: "2021",
    km: "3.500 km",
    transmission: "Otomatis",
    location: "Simpang Kandis",
    fullLocation: "Simpang Kandis, Bengkulu",
    color: "Hitam Biru",
    engine: "155cc",
    condition: "Bekas",
    image: "/id4.png",
    description:
      "Yamaha Aerox 155 dengan desain sporty, mesin bertenaga, dan cocok digunakan untuk mobilitas harian maupun touring.",
  },
  {
    id: 5,
    name: "Honda Scoopy",
    price: "Rp 18.000.000",
    type: "Matic",
    year: "2018",
    km: "15.000 km",
    transmission: "Otomatis",
    location: "Simpang Kandis",
    fullLocation: "Simpang Kandis, Bengkulu",
    color: "Merah Hitam",
    engine: "110cc",
    condition: "Bekas",
    image: "/id5.png",
    description:
      "Honda Scoopy dengan desain retro modern yang stylish dan mesin 110cc yang irit bahan bakar. Cocok digunakan untuk aktivitas sehari-hari, nyaman dikendarai, serta mudah dalam perawatan.",
  },

  {
    id: 6,
    name: "Honda PCX 160",
    price: "Rp 35.000.000",
    type: "Matic",
    year: "2023",
    km: "6.800 km",
    transmission: "Otomatis",
    location: "Simpang Kandis",
    fullLocation: "Simpang Kandis, Bengkulu",
    color: "Putih",
    engine: "160cc",
    condition: "Bekas",
    image: "/id6.png",
    description:
      "Honda PCX 160 dengan desain premium, nyaman digunakan untuk perjalanan jauh maupun aktivitas sehari-hari.",
  },

  {
    id: 7,
    name: "Yamaha Vega ZR Merah",
    price: "Rp 6.700.000",
    type: "Bebek",
    year: "2011",
    km: "15.000 km",
    transmission: "Manual",
    location: "Seluma",
    fullLocation: "Seluma, Bengkulu",
    color: "Merah Putih",
    engine: "113,7cc",
    condition: "Bekas",
    image: "/id7.png",
    description:
      "Yamaha Vega ZR berwarna merah putih dengan kondisi bekas yang masih terawat. Motor bebek ini menggunakan mesin 113,7cc yang terkenal irit bahan bakar, tangguh, dan mudah dalam perawatan. Cocok digunakan untuk kebutuhan transportasi sehari-hari maupun perjalanan jarak menengah.",
  },

  {
    id: 8,
    name: "Yamaha NMAX 155 ABS",
    price: "Rp 36.500.000",
    type: "Matic",
    year: "2023",
    km: "4.100 km",
    transmission: "Otomatis",
    location: "Simpang Kandis",
    fullLocation: "Simpang Kandis, Bengkulu",
    color: "Hitam",
    engine: "155cc ABS",
    condition: "Bekas",
    image: "/id8.png",
    description:
      "Yamaha NMAX 155 ABS dengan fitur pengereman ABS, nyaman digunakan untuk perjalanan jauh maupun mobilitas sehari-hari.",
  },
];
