// src/data/MotorData.tsx

export const allMotors = [
  {
    id: 1,
    name: "Honda Vario 160",
    price: "Rp 28.500.000",
    type: "Matic",
    year: "2023",
    km: "5.200 km",
    transmission: "Otomatis",
    location: "Sleman",
    fullLocation: "Sleman, Yogyakarta",
    color: "Merah",
    engine: "156.9cc, DOHC eSP+",
    condition: "Bekas",
    image: "/vario160.jpg",
    description: "Honda Vario 160 2023 kondisi sangat mulus, tangan pertama, surat lengkap STNK & BPKB asli. Ban baru, mesin halus, bodi mulus tanpa lecet. Siap pakai langsung."
  },
  {
    id: 2,
    name: "Yamaha NMAX 155",
    price: "Rp 32.000.000",
    type: "Matic",
    year: "2022",
    km: "12.000 km",
    transmission: "Otomatis",
    location: "Bantul",
    fullLocation: "Bantul, Yogyakarta",
    color: "Hitam Matte",
    engine: "155cc, Liquid Cooled",
    condition: "Bekas",
    image: "/nmax155.jpg",
    description: "Yamaha NMAX 155 tahun 2022. Kondisi terawat, mesin standar, servis rutin di bengkel resmi. Kelistrikan normal semua."
  },
  {
    id: 3,
    name: "Honda Beat Street",
    price: "Rp 15.500.000",
    type: "Matic",
    year: "2022",
    km: "8.700 km",
    transmission: "Otomatis",
    location: "Yogyakarta",
    fullLocation: "Kota Yogyakarta",
    color: "Hitam",
    engine: "110cc, eSP",
    condition: "Bekas",
    image: "/beatstreet.jpg",
    description: "Beat Street 2022, pemakaian wajar untuk harian. Pajak hidup, surat lengkap. Sangat irit dan gesit."
  },
  {
    id: 4,
    name: "Yamaha Aerox 155",
    price: "Rp 26.000.000",
    type: "Matic",
    year: "2023",
    km: "3.500 km",
    transmission: "Otomatis",
    location: "Sleman",
    fullLocation: "Sleman, Yogyakarta",
    color: "Biru",
    engine: "155cc, VVA",
    condition: "Bekas",
    image: "/aerox155.jpg",
    description: "Aerox 155 Connected, seperti baru! Km rendah, motor simpanan, bodi kinclong tanpa goresan."
  },
  {
    id: 5,
    name: "Kawasaki Ninja 250",
    price: "Rp 55.000.000",
    type: "Sport",
    year: "2021",
    km: "9.000 km",
    transmission: "Manual",
    location: "Sleman",
    fullLocation: "Sleman, Yogyakarta",
    color: "Hijau",
    engine: "250cc, 2-Cylinder",
    condition: "Bekas",
    image: "/ninja250.jpg",
    description: "Ninja 250 FI. Mesin sehat, suara gahar. Modifikasi ringan pada knalpot, part original masih tersimpan rapi."
  },
  {
    id: 6,
    name: "Honda PCX 160",
    price: "Rp 34.000.000",
    type: "Matic",
    year: "2023",
    km: "4.000 km",
    transmission: "Otomatis",
    location: "Bantul",
    fullLocation: "Bantul, Yogyakarta",
    color: "Putih",
    engine: "160cc, 4-Katup",
    condition: "Bekas",
    image: "/pcx160.jpg",
    description: "PCX 160 ABS, kondisi sangat prima. Nyaman untuk perjalanan jauh. Tangan pertama."
  },
  {
    id: 7,
    name: "Yamaha Fazzio",
    price: "Rp 20.500.000",
    type: "Matic",
    year: "2024",
    km: "1.200 km",
    transmission: "Otomatis",
    location: "Yogyakarta",
    fullLocation: "Kota Yogyakarta",
    color: "Beige",
    engine: "125cc, Blue Core Hybrid",
    condition: "Bekas",
    image: "/fazzio.jpg",
    description: "Yamaha Fazzio Hybrid. Masih sangat baru, jarang dipakai. Garansi resmi masih panjang."
  },
  {
    id: 8,
    name: "Honda CRF 150L",
    price: "Rp 30.000.000",
    type: "Trail",
    year: "2022",
    km: "11.000 km",
    transmission: "Manual",
    location: "Sleman",
    fullLocation: "Sleman, Yogyakarta",
    color: "Merah Putih",
    engine: "150cc, PGM-FI",
    condition: "Bekas",
    image: "/crf150.jpg",
    description: "CRF 150L cocok untuk medan offroad ringan maupun harian. Kaki-kaki aman, mesin tangguh."
  },
  {
    id: 9,
    name: "Suzuki Satria FU",
    price: "Rp 12.000.000",
    type: "Bebek",
    year: "2020",
    km: "20.000 km",
    transmission: "Manual",
    location: "Bantul",
    fullLocation: "Bantul, Yogyakarta",
    color: "Hitam",
    engine: "150cc, DOHC",
    condition: "Bekas",
    image: "/satria.jpg",
    description: "Satria FU 150 Injeksi. Tarikan enteng, mesin kering tidak ada rembes."
  },
  {
    id: 10,
    name: "Yamaha R15",
    price: "Rp 23.000.000",
    type: "Sport",
    year: "2021",
    km: "15.000 km",
    transmission: "Manual",
    location: "Yogyakarta",
    fullLocation: "Kota Yogyakarta",
    color: "Biru",
    engine: "155cc, VVA",
    condition: "Bekas",
    image: "/r15.jpg",
    description: "Yamaha R15 V3. Tampilan sporty, kondisi standar pabrik. Ban sudah ganti baru."
  },
  {
    id: 11,
    name: "Honda Scoopy",
    price: "Rp 19.500.000",
    type: "Matic",
    year: "2023",
    km: "6.000 km",
    transmission: "Otomatis",
    location: "Sleman",
    fullLocation: "Sleman, Yogyakarta",
    color: "Cream",
    engine: "110cc, eSP",
    condition: "Bekas",
    image: "/scoopy.jpg",
    description: "Scoopy Prestige 2023. Desain retro elegan, kondisi sangat terawat untuk penggunaan dalam kota."
  },
  {
    id: 12,
    name: "Vespa LX 125",
    price: "Rp 38.000.000",
    type: "Matic",
    year: "2022",
    km: "7.500 km",
    transmission: "Otomatis",
    location: "Yogyakarta",
    fullLocation: "Kota Yogyakarta",
    color: "Abu-abu",
    engine: "125cc, I-Get",
    condition: "Bekas",
    image: "/vespa.jpg",
    description: "Vespa LX 125 I-Get. Motor ikonik, sangat nyaman dan stylish. Kelengkapan dokumen aman."
  }
];